name: Backup to Git

on:
  push:
    branches: [main]

jobs:
  pierre:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4

      - name: Push to Pierre 💖
        uses: jenkins-zh/git-backup-actions@v0.0.1
        env:
          GIT_DEPLOY_KEY: ${{ secrets.PIERRE_SSH_KEY }}
          TARGET_GIT: "git@git.pierre.co:hey/hey.git"
          BRANCH: main
