name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js, pnpm and dependencies 🌸
        uses: ./.github/actions/setup-pnpm

      - name: Typecheck 🔡
        run: pnpm typecheck

  # biome:
  #   name: Biome
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout 🚪
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Setup Node.js, pnpm and dependencies 🌸
  #       uses: ./.github/actions/setup-pnpm

  #     - name: Biome 🪩
  #       run: pnpm biome:check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🚪
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js, pnpm and dependencies 🌸
        uses: ./.github/actions/setup-pnpm

      - name: Build 🎁
        run: pnpm build
