name: Remove Codex Label

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

permissions:
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(label => label.name);
            const codexLabels = labels.filter(name => name.toLowerCase().includes('codex'));

            if (codexLabels.length === 0) {
              core.info('No codex label found.');
              return;
            }

            for (const label of codexLabels) {
              try {
                await github.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  name: label,
                });
                core.info(`Removed label: ${label}`);
              } catch (error) {
                core.warning(`Failed to remove label: ${label}`);
              }
            }
