name: Remove Codex Label

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

permissions:
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(label => label.name);
            core.info(`Found labels on PR: ${JSON.stringify(labels)}`);

            const codexLabels = labels.filter(name => name.toLowerCase().includes('codex'));
            core.info(`Codex labels detected: ${JSON.stringify(codexLabels)}`);

            if (codexLabels.length > 0) {
              for (const label of codexLabels) {
                try {
                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    name: label,
                  });
                  core.info(`✅ Removed label: ${label}`);
                } catch (err) {
                  core.warning(`❌ Failed to remove label "${label}": ${err.message}`);
                }
              }
            }

            const originalBody = pr.body || '';
            const cleanedBody = originalBody.replace(/.*codex.*\n?/gi, '').trim();

            if (cleanedBody !== originalBody) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                body: cleanedBody,
              });
              core.info('🧹 Cleaned PR description from codex lines.');
            } else {
              core.info('No codex lines found in description.');
            }
