name: Save to Software Heritage

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  swh:
    runs-on: ubuntu-latest
    steps:
      - name: Save to Software Heritage
        uses: sdruskat/swh-save-action@v1.0.1
